apiVersion: apps/v1
kind: ReplicaSet

metadata:
  name: nginx
  # ReplicaSet labels
  labels:
    purpose: rs-demo
    project: roboshop
    app: nginx

spec:
  replicas: 3

  # These labels are used by ReplicaSet to select Pods.
  # They must match the Pod template labels.
  selector:
    matchLabels:
      purpose: rs-demo
      project: roboshop
      app: nginx

  # Pod definition
  template:
    metadata:
      labels:
        purpose: rs-demo
        project: roboshop
        app: nginx

    spec:
      containers:
        - name: nginx
          image: nginx